"""Add ON DELETE SET NULL to staff_user_id and adopter_user_id FKs

Revision ID: d66041875640
Revises: 2ce4d8cbda92
Create Date: 2025-11-07 22:02:59.469792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd66041875640'
down_revision: Union[str, Sequence[str], None] = '2ce4d8cbda92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adoptionrequest', 'adopter_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('adoptionrequest_adopter_user_id_fkey'), 'adoptionrequest', type_='foreignkey')
    op.create_foreign_key(None, 'adoptionrequest', 'user', ['adopter_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('medicalrecord', 'staff_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('medicalrecord_staff_user_id_fkey'), 'medicalrecord', type_='foreignkey')
    op.create_foreign_key(None, 'medicalrecord', 'user', ['staff_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('org_admin', 'staff', 'adopter', name='userrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vaccination', 'staff_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('vaccination_staff_user_id_fkey'), 'vaccination', type_='foreignkey')
    op.create_foreign_key(None, 'vaccination', 'user', ['staff_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccination', type_='foreignkey')
    op.create_foreign_key(op.f('vaccination_staff_user_id_fkey'), 'vaccination', 'user', ['staff_user_id'], ['id'])
    op.alter_column('vaccination', 'staff_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('org_admin', 'staff', 'adopter', name='userrole'),
               server_default=sa.text("'adopter'::userrole"),
               existing_nullable=False)
    op.drop_constraint(None, 'medicalrecord', type_='foreignkey')
    op.create_foreign_key(op.f('medicalrecord_staff_user_id_fkey'), 'medicalrecord', 'user', ['staff_user_id'], ['id'])
    op.alter_column('medicalrecord', 'staff_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'adoptionrequest', type_='foreignkey')
    op.create_foreign_key(op.f('adoptionrequest_adopter_user_id_fkey'), 'adoptionrequest', 'user', ['adopter_user_id'], ['id'])
    op.alter_column('adoptionrequest', 'adopter_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
